# Generated by Django 5.2 on 2025-10-17 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                (
                    "is_read_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if staff has read the latest messages",
                        verbose_name="Read by Staff",
                    ),
                ),
                (
                    "is_read_customer",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if customer has read the latest messages",
                        verbose_name="Read by Customer",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this chat room is currently active",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The customer who owns this chat room",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_chat_rooms",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Room Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Room",
                "verbose_name_plural": "Chat Rooms",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("customer", "Customer Message"),
                            ("staff", "Staff Message"),
                            ("system", "System Message"),
                        ],
                        default="customer",
                        max_length=10,
                        verbose_name="Message Type",
                    ),
                ),
                ("message", models.TextField(verbose_name="Message Content")),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Sent At"),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who sent the message (null for system messages)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_chat_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sender",
                    ),
                ),
                (
                    "chat_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_items",
                        to="api.chatroom",
                        verbose_name="Chat Room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Item",
                "verbose_name_plural": "Chat Items",
                "ordering": ["sent_at"],
            },
        ),
        migrations.DeleteModel(
            name="ChatMessage",
        ),
    ]
