# Generated by Django 5.2 on 2025-10-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_chatroom_chatitem_delete_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="productlisting",
            name="bike_builder_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Make this product available in the bike builder wizard",
                verbose_name="Enable in Bike Builder",
            ),
        ),
        migrations.AddField(
            model_name="productlisting",
            name="builder_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("frame", "Frame"),
                    ("fork", "Fork"),
                    ("wheels", "Wheels"),
                    ("drivetrain", "Drivetrain"),
                    ("brakes", "Brakes"),
                    ("handlebars", "Handlebars"),
                    ("saddle", "Saddle"),
                    ("pedals", "Pedals"),
                    ("accessories", "Accessories"),
                ],
                help_text="Category for bike builder wizard",
                max_length=50,
                null=True,
                verbose_name="Builder Category",
            ),
        ),
        migrations.AddField(
            model_name="productlisting",
            name="builder_priority",
            field=models.IntegerField(
                default=0,
                help_text="Display order in bike builder (higher = shows first)",
                verbose_name="Builder Priority",
            ),
        ),
    ]
