# Generated by Django 5.2 on 2025-10-20 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_productlisting_bike_builder_enabled_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productcategory",
            options={
                "ordering": ["name"],
                "verbose_name": "Product Category",
                "verbose_name_plural": "Product Categories",
            },
        ),
        migrations.AddField(
            model_name="productcategory",
            name="component_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("frame", "Frame"),
                    ("fork", "Fork"),
                    ("wheels", "Wheels"),
                    ("drivetrain", "Drivetrain"),
                    ("brakes", "Brakes"),
                    ("handlebars", "Handlebars"),
                    ("saddle", "Saddle"),
                    ("pedals", "Pedals"),
                    ("accessories", "Accessories"),
                ],
                help_text="Type of component (only for component categories)",
                max_length=50,
                null=True,
                verbose_name="Component Type",
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="is_component",
            field=models.BooleanField(
                default=False,
                help_text="Check if this is a bike component category (frame, wheels, etc.)",
                verbose_name="Is Component Category",
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave blank for top-level categories",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="api.productcategory",
                verbose_name="Parent Category",
            ),
        ),
    ]
