# Generated by Django 5.2 on 2025-10-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_productcategory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cancel_reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="Cancellation Reason"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="return_reason",
            field=models.TextField(blank=True, null=True, verbose_name="Return Reason"),
        ),
    ]
