# Generated by Django 5.2 on 2025-10-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_order_cancel_reason_order_return_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="sales",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("card", "Credit/Debit Card"),
                    ("gcash", "GCash"),
                    ("paymaya", "PayMaya"),
                    ("bank_transfer", "Bank Transfer"),
                ],
                default="cash",
                max_length=50,
                verbose_name="Payment Method",
            ),
        ),
    ]
