# Generated by Django 5.2 on 2025-10-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_sales_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesitem",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Total amount for this item (negative for refunds)",
                max_digits=10,
                null=True,
                verbose_name="Amount",
            ),
        ),
    ]
