# Generated by Django 5.2 on 2025-05-20 15:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_cart_created_at_cart_updated_at_order_orderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="cart",
        ),
    ]
