# Generated by Django 5.2 on 2025-05-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_remove_order_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.BooleanField(default=True, verbose_name="Active Status"),
        ),
    ]
