# Generated by Django 5.2 on 2025-10-24 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_salesitem_amount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("purchased", "Purchased"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "queue_position",
                    models.IntegerField(
                        default=0, help_text="Position in the reservation queue"
                    ),
                ),
                (
                    "reserved_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the active reservation expires (3 days from activation)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether user has been notified about active reservation",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="api.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["queue_position", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "status"],
                        name="api_product_product_74ed0c_idx",
                    ),
                    models.Index(
                        fields=["user", "status"], name="api_product_user_id_d0882b_idx"
                    ),
                ],
                "unique_together": {("user", "product", "status")},
            },
        ),
    ]
