# Generated by Django 5.2 on 2025-05-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_product_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.BooleanField(default=True, verbose_name="Available"),
        ),
    ]
