# Generated by Django 5.2 on 2025-10-24 22:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_productreservation"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductReservation",
        ),
    ]
