# Generated by Django 5.2 on 2025-05-20 15:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_product_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="status",
            new_name="available",
        ),
    ]
