# Generated by Django 5.2 on 2025-10-24 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_delete_productreservation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservedproduct",
            options={"ordering": ["product", "queue_position", "created_at"]},
        ),
        migrations.AddField(
            model_name="reservedproduct",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True, help_text="When the reservation was cancelled", null=True
            ),
        ),
        migrations.AddField(
            model_name="reservedproduct",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="When the reservation was created",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reservedproduct",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the active reservation expires (3 days after reserved_at)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reservedproduct",
            name="fulfilled_at",
            field=models.DateTimeField(
                blank=True, help_text="When the user purchased the product", null=True
            ),
        ),
        migrations.AddField(
            model_name="reservedproduct",
            name="queue_position",
            field=models.IntegerField(
                default=0, help_text="Position in the reservation queue (1 = first)"
            ),
        ),
        migrations.AddField(
            model_name="reservedproduct",
            name="reserved_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the reservation became active (product became available)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reservedproduct",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting in Queue"),
                    ("active", "Active Reservation"),
                    ("expired", "Expired"),
                    ("fulfilled", "Fulfilled"),
                    ("cancelled", "Cancelled"),
                ],
                default="waiting",
                help_text="Current status of the reservation",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reservedproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="api.product",
            ),
        ),
        migrations.AlterField(
            model_name="reservedproduct",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_reservations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reservedproduct",
            unique_together={("product", "user")},
        ),
    ]
