# Generated by Django 5.2 on 2025-10-25 00:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_alter_reservedproduct_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paymongo_payment_id",
            field=models.CharField(
                blank=True,
                help_text="Payment ID from PayMongo checkout session",
                max_length=255,
                null=True,
                verbose_name="PayMongo Payment ID",
            ),
        ),
    ]
