# Generated by Django 5.2 on 2025-10-25 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_order_paymongo_payment_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffPermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "can_access_pos",
                    models.BooleanField(default=True, verbose_name="POS Access"),
                ),
                (
                    "can_access_chats",
                    models.BooleanField(default=True, verbose_name="Chat Access"),
                ),
                (
                    "can_access_orders",
                    models.BooleanField(default=True, verbose_name="Orders Access"),
                ),
                (
                    "can_access_listings",
                    models.BooleanField(default=True, verbose_name="Listings Access"),
                ),
                (
                    "can_access_inventory",
                    models.BooleanField(default=True, verbose_name="Inventory Access"),
                ),
                (
                    "can_access_queueing",
                    models.BooleanField(
                        default=True, verbose_name="Service Queue Access"
                    ),
                ),
                (
                    "can_access_reservations",
                    models.BooleanField(
                        default=True, verbose_name="Reservations Access"
                    ),
                ),
                (
                    "can_access_suppliers",
                    models.BooleanField(default=True, verbose_name="Suppliers Access"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"is_staff": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Permission",
                "verbose_name_plural": "Staff Permissions",
            },
        ),
    ]
