# Generated by Django 5.2 on 2025-07-06 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_brands"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brands",
            options={
                "ordering": ["name"],
                "verbose_name": "Brand",
                "verbose_name_plural": "Brands",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.brands",
                verbose_name="Brand",
            ),
        ),
    ]
