# Generated by Django 5.2 on 2025-10-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_staffpermissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="compatibilityattribute",
            options={
                "ordering": ["group__name", "name"],
                "verbose_name": "Compatibility Attribute (Deprecated)",
                "verbose_name_plural": "Compatibility Attributes (Deprecated)",
            },
        ),
        migrations.AlterModelOptions(
            name="compatibilityattributevalue",
            options={
                "ordering": ["attribute", "display_name"],
                "verbose_name": "Compatibility Attribute Value (Deprecated)",
                "verbose_name_plural": "Compatibility Attribute Values (Deprecated)",
            },
        ),
        migrations.AlterModelOptions(
            name="compatibilitygroup",
            options={
                "ordering": ["name"],
                "verbose_name": "Compatibility Group (Deprecated)",
                "verbose_name_plural": "Compatibility Groups (Deprecated)",
            },
        ),
        migrations.RemoveField(
            model_name="productlisting",
            name="compatibility_attributes",
        ),
        migrations.RemoveField(
            model_name="productlisting",
            name="compatible_with",
        ),
        migrations.AlterField(
            model_name="productlisting",
            name="builder_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("frame", "Frame"),
                    ("wheels", "Wheels"),
                    ("drivetrain", "Drivetrain"),
                    ("brakes", "Brakes"),
                    ("handlebars", "Handlebars"),
                    ("saddle", "Saddle"),
                ],
                help_text="Component type for bike builder (Frame, Wheels, etc.)",
                max_length=50,
                null=True,
                verbose_name="Builder Category",
            ),
        ),
        migrations.CreateModel(
            name="BikeCompatibilityTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag_type",
                    models.CharField(
                        choices=[
                            ("use_case", "Use Case"),
                            ("budget", "Budget Range"),
                            ("physical", "Physical Compatibility"),
                        ],
                        help_text="Type of compatibility tag",
                        max_length=20,
                        verbose_name="Tag Type",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Internal value (e.g., 'city', 'budget', 'disc_brake')",
                        max_length=100,
                        verbose_name="Value",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="User-friendly name (e.g., 'City Commuting', 'Budget ₱15k-24k')",
                        max_length=255,
                        verbose_name="Display Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description for this tag",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order to display (higher = shows first)",
                        verbose_name="Display Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bike Compatibility Tag",
                "verbose_name_plural": "Bike Compatibility Tags",
                "ordering": ["tag_type", "-display_order", "display_name"],
                "unique_together": {("tag_type", "value")},
            },
        ),
        migrations.AddField(
            model_name="productlisting",
            name="compatibility_tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select use case, budget range, and physical compatibility tags for this product",
                related_name="products",
                to="api.bikecompatibilitytag",
                verbose_name="Compatibility Tags",
            ),
        ),
    ]
