# Generated by Django 5.2 on 2025-07-06 19:05

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_alter_brands_options_product_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brands",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="name", unique=True, verbose_name="Slug"
            ),
        ),
    ]
