# Generated by Django 5.2 on 2025-10-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_alter_compatibilityattribute_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productlisting",
            name="compatibility_attributes",
            field=models.ManyToManyField(
                blank=True,
                help_text="DEPRECATED: Use compatibility_tags instead",
                related_name="products_with_attribute",
                to="api.compatibilityattributevalue",
                verbose_name="Product Attributes (Deprecated)",
            ),
        ),
        migrations.AddField(
            model_name="productlisting",
            name="compatible_with",
            field=models.ManyToManyField(
                blank=True,
                help_text="DEPRECATED: Use compatibility_tags instead",
                related_name="compatible_products",
                to="api.compatibilityattributevalue",
                verbose_name="Compatible With (Deprecated)",
            ),
        ),
    ]
