# Generated by Django 5.2 on 2025-10-30 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_productlisting_compatibility_attributes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sales",
            name="salesperson",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member who processed this sale (POS only, None for online sales)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_as_salesperson",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Salesperson",
            ),
        ),
    ]
