# Generated by Django 5.2 on 2025-10-31 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_sales_salesperson"),
    ]

    operations = [
        migrations.AddField(
            model_name="sales",
            name="last_modified",
            field=models.DateTimeField(auto_now=True, verbose_name="Last Modified"),
        ),
        migrations.AddField(
            model_name="sales",
            name="order",
            field=models.OneToOneField(
                blank=True,
                help_text="Linked order (1 Order = 1 Sale)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.order",
                verbose_name="Related Order",
            ),
        ),
        migrations.AddField(
            model_name="salesitem",
            name="refunded",
            field=models.BooleanField(
                default=False,
                help_text="True if all units of this item have been refunded",
                verbose_name="Refunded",
            ),
        ),
        migrations.AddField(
            model_name="salesitem",
            name="refunded_quantity",
            field=models.IntegerField(
                default=0,
                help_text="Number of units refunded for this item",
                verbose_name="Refunded Quantity",
            ),
        ),
        migrations.AddField(
            model_name="salesitem",
            name="supplier_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Supplier price at time of sale (snapshot, doesn't change)",
                max_digits=10,
                null=True,
                verbose_name="Supplier Price",
            ),
        ),
    ]
