# Generated by Django 5.2 on 2025-10-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_sales_last_modified_sales_order_salesitem_refunded_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_order_updates",
            field=models.BooleanField(
                default=True,
                help_text="Receive emails when your orders are completed",
                verbose_name="Order Update Notifications",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_reservation_updates",
            field=models.BooleanField(
                default=True,
                help_text="Receive emails when your reservations are fulfilled",
                verbose_name="Reservation Update Notifications",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_service_updates",
            field=models.BooleanField(
                default=True,
                help_text="Receive emails when your service appointments are completed",
                verbose_name="Service Update Notifications",
            ),
        ),
    ]
