# Generated by Django 5.2 on 2025-11-07 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_userprofile_email_order_updates_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        blank=True,
                        help_text="Feature area where the event occurred (e.g., inventory, sales)",
                        max_length=50,
                        verbose_name="Module",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Short identifier describing what happened",
                        max_length=150,
                        verbose_name="Action",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Human-friendly summary of the event",
                        verbose_name="Description",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="Severity",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured details about the event",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "target_object_id",
                    models.CharField(
                        blank=True,
                        help_text="Identifier of the affected object, if available",
                        max_length=255,
                        null=True,
                        verbose_name="Target Object ID",
                    ),
                ),
                (
                    "target_object_repr",
                    models.CharField(
                        blank=True,
                        help_text="Readable representation of the affected object",
                        max_length=255,
                        verbose_name="Target Object",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Origin IP address when the action was performed",
                        null=True,
                        verbose_name="IP Address",
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        help_text="Browser or client that triggered the action",
                        max_length=255,
                        verbose_name="User Agent",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action (null for system events)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="api_auditlo_created_f26dbe_idx"
                    ),
                    models.Index(
                        fields=["module"], name="api_auditlo_module_d06630_idx"
                    ),
                    models.Index(
                        fields=["action"], name="api_auditlo_action_0a1743_idx"
                    ),
                ],
            },
        ),
    ]
