# Generated by Django 5.2 on 2025-07-06 19:45

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="name", unique_with=("brand",)
            ),
        ),
    ]
