# Generated by Django 5.2 on 2025-07-06 19:46

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brands",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="name", unique_with=("brand__name",)
            ),
        ),
    ]
