# Generated by Django 5.2 on 2025-07-06 20:50

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_alter_brands_name_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=tinymce.models.HTMLField(
                blank=True, null=True, verbose_name="Product Description"
            ),
        ),
    ]
