# Generated by Django 5.2 on 2025-07-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0021_productvariant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Price",
            ),
        ),
    ]
