# Generated by Django 5.2 on 2025-07-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0022_alter_product_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariant",
            name="color",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="size",
        ),
        migrations.AddField(
            model_name="productvariant",
            name="variant",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Variant Name"
            ),
        ),
    ]
