# Generated by Django 5.2 on 2025-07-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0023_remove_productvariant_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="variant",
            field=models.CharField(
                blank=True,
                default="None",
                max_length=255,
                null=True,
                verbose_name="Variant Name",
            ),
        ),
    ]
