# Generated by Django 5.2 on 2025-07-07 09:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0024_alter_productvariant_variant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
    ]
