# Generated by Django 5.2 on 2025-07-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0025_remove_product_price_remove_product_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompatibilityAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Attribute Name"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
                ),
            ],
            options={
                "verbose_name": "Compatibility Attribute",
                "verbose_name_plural": "Compatibility Attributes",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="compatibility",
            field=models.ManyToManyField(
                blank=True,
                to="api.compatibilityattribute",
                verbose_name="Compatibility Attributes",
            ),
        ),
    ]
