# Generated by Django 5.2 on 2025-07-08 18:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0026_compatibilityattribute_product_compatibility"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="compatibilityattribute",
            name="slug",
        ),
    ]
