# Generated by Django 5.2 on 2025-07-08 19:54

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0027_remove_compatibilityattribute_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcategory",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="name", unique=True
            ),
        ),
    ]
