# Generated by Django 5.2 on 2025-07-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0029_productimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/",
                verbose_name="Product Card Image",
            ),
        ),
    ]
