# Generated by Django 5.2 on 2025-07-17 21:56

import api.models
import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0030_alter_productimage_options_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="name", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to=api.models.upload_to_product_folder),
        ),
    ]
