# Generated by Django 5.2 on 2025-07-22 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0031_alter_product_slug_alter_productimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.productvariant",
                verbose_name="Product",
            ),
        ),
    ]
