# Generated by Django 5.2 on 2025-07-22 06:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0035_remove_cartitem_product_cartitem_product_variant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="product_variant",
        ),
    ]
