# Generated by Django 5.2 on 2025-07-22 19:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0036_remove_cartitem_product_variant"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
