# Generated by Django 5.2 on 2025-07-26 06:24

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0038_cartitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariant",
            name="image",
        ),
        migrations.CreateModel(
            name="ProductVariantImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=api.models.upload_to_product_folder),
                ),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                (
                    "product_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="api.productvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Variant Image",
                "verbose_name_plural": "Product Variant Images",
            },
        ),
    ]
