# Generated by Django 5.2 on 2025-07-26 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0039_remove_productvariant_image_productvariantimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariantimage",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test",
                to="api.product",
            ),
        ),
    ]
