# Generated by Django 5.2 on 2025-07-26 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0040_productvariantimage_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariantimage",
            name="product_variant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="api.productvariant",
            ),
        ),
    ]
