# Generated by Django 5.2 on 2025-07-26 06:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0041_alter_productvariantimage_product_variant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariantimage",
            name="product",
        ),
    ]
