# Generated by Django 5.2 on 2025-07-26 12:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0043_productvariantimage_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariantimage",
            name="product",
        ),
    ]
