# Generated by Django 5.2 on 2025-07-27 09:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0044_remove_productvariantimage_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productvariantimage",
            old_name="product_variant",
            new_name="product",
        ),
    ]
