# Generated by Django 5.2 on 2025-07-27 09:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0045_rename_product_variant_productvariantimage_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productvariantimage",
            old_name="product",
            new_name="product_variant",
        ),
    ]
