# Generated by Django 5.2 on 2025-07-30 10:09

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0046_rename_product_productvariantimage_product_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Lowest Variant Price",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=api.models.upload_to_product_folder,
                verbose_name="Product Card Image",
            ),
        ),
    ]
