# Generated by Django 5.2 on 2025-08-05 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0048_alter_product_price_productreview"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productvariant",
            old_name="variant",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="productvariantimage",
            name="product_variant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variant_images",
                to="api.productvariant",
            ),
        ),
    ]
