# Generated by Django 5.2 on 2025-08-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0049_rename_variant_productvariant_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="sku",
            field=models.CharField(blank=True, null=True, verbose_name="SKU"),
        ),
    ]
