# Generated by Django 5.2 on 2025-08-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0052_alter_productreview_star"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productreview",
            name="star",
            field=models.IntegerField(
                choices=[
                    (1, "1 star"),
                    (2, "2 star"),
                    (3, "3 star"),
                    (4, "4 star"),
                    (5, "5 star"),
                ]
            ),
        ),
    ]
