# Generated by Django 5.2 on 2025-08-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0053_alter_productreview_star"),
    ]

    operations = [
        migrations.AddField(
            model_name="productreview",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
