# Generated by Django 5.2 on 2025-08-07 12:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0054_productreview_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="product_variant",
            new_name="product",
        ),
    ]
