# Generated by Django 5.2 on 2025-08-08 15:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0056_cartitem_product_variant_alter_cartitem_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
    ]
