# Generated by Django 5.2 on 2025-08-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0058_sales_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("returned", "Returned"),
                ],
                default="pending",
                max_length=50,
                verbose_name="Order Status",
            ),
        ),
    ]
