# Generated by Django 5.2 on 2025-08-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0061_servicequeue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicequeue",
            name="queue_date",
            field=models.DateField(verbose_name="Queue Date"),
        ),
    ]
