# Generated by Django 5.2 on 2025-08-26 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0062_alter_servicequeue_queue_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="api.product",
                verbose_name="Product",
            ),
        ),
    ]
