# Generated by Django 5.2 on 2025-08-27 14:16

import api.models
import autoslug.fields
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0063_alter_productvariant_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="product_variant",
        ),
        migrations.RemoveField(
            model_name="productvariantimage",
            name="product_variant",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product_variant",
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "verbose_name": "Product Listing Image",
                "verbose_name_plural": "Product Listing Images",
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="brand",
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="compatibility",
        ),
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.RemoveField(
            model_name="product",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productreview",
            name="product",
        ),
        migrations.RemoveField(
            model_name="sales",
            name="product",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.product",
                verbose_name="Product",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.product",
                verbose_name="Item",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(blank=True, null=True, verbose_name="SKU"),
        ),
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.IntegerField(default=0, verbose_name="Stock Quantity"),
        ),
        migrations.AddField(
            model_name="productvariantimage",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variant_images",
                to="api.product",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                blank=True,
                default="None",
                max_length=255,
                null=True,
                verbose_name="Variant Name",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=10, verbose_name="Price"
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ProductListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Product Name")),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Lowest Variant Price",
                    ),
                ),
                (
                    "description",
                    tinymce.models.HTMLField(
                        blank=True, null=True, verbose_name="Product Description"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=api.models.upload_to_product_folder,
                        verbose_name="Product Card Image",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                (
                    "available",
                    models.BooleanField(default=True, verbose_name="Available"),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.brands",
                        verbose_name="Brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.productcategory",
                        verbose_name="Category",
                    ),
                ),
                (
                    "compatibility",
                    models.ManyToManyField(
                        blank=True,
                        to="api.compatibilityattribute",
                        verbose_name="Compatibility Attributes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Listing",
                "verbose_name_plural": "Product Listings",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="product_listing",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="api.productlisting",
                verbose_name="Product Listing",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="product_listing",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="api.productlisting",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productreview",
            name="product_listing",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="api.productlisting",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sales",
            name="product_listing",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.productlisting",
                verbose_name="Product Listing",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="ProductVariant",
        ),
    ]
