# Generated by Django 5.2 on 2025-08-27 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0064_remove_cartitem_product_variant_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productlisting",
            name="brand",
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.brands",
                verbose_name="Brand",
            ),
        ),
    ]
