# Generated by Django 5.2 on 2025-08-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0065_remove_productlisting_brand_product_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="variant_attribute",
            field=models.CharField(
                blank=True, default="None", null=True, verbose_name="Color"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Variant Name"
            ),
        ),
    ]
