# Generated by Django 5.2 on 2025-08-27 15:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0066_product_variant_attribute_alter_product_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productlisting",
            name="name",
        ),
    ]
