# Generated by Django 5.2 on 2025-08-27 15:28

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0067_remove_productlisting_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompatibilityGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Group Name")),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from="name",
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Compatibility Group",
                "verbose_name_plural": "Compatibility Groups",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="compatibilityattribute",
            options={
                "ordering": ["group__name", "name"],
                "verbose_name": "Compatibility Attribute",
                "verbose_name_plural": "Compatibility Attributes",
            },
        ),
        migrations.RemoveField(
            model_name="productlisting",
            name="compatibility",
        ),
        migrations.AddField(
            model_name="compatibilityattribute",
            name="attribute_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("number", "Number"),
                    ("boolean", "Yes/No"),
                    ("choice", "Multiple Choice"),
                ],
                default="text",
                max_length=50,
                verbose_name="Attribute Type",
            ),
        ),
        migrations.AddField(
            model_name="compatibilityattribute",
            name="is_required",
            field=models.BooleanField(default=False, verbose_name="Required"),
        ),
        migrations.CreateModel(
            name="CompatibilityAttributeChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(max_length=255, verbose_name="Choice Value"),
                ),
                (
                    "display_name",
                    models.CharField(max_length=255, verbose_name="Display Name"),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="api.compatibilityattribute",
                        verbose_name="Attribute",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attribute Choice",
                "verbose_name_plural": "Attribute Choices",
                "ordering": ["attribute", "display_name"],
                "unique_together": {("attribute", "value")},
            },
        ),
        migrations.AddField(
            model_name="compatibilityattribute",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributes",
                to="api.compatibilitygroup",
                verbose_name="Compatibility Group",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="compatibilityattribute",
            unique_together={("group", "name")},
        ),
        migrations.CreateModel(
            name="ProductCompatibilityValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_value", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "number_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("boolean_value", models.BooleanField(blank=True, null=True)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.compatibilityattribute",
                        verbose_name="Attribute",
                    ),
                ),
                (
                    "choice_value",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.compatibilityattributechoice",
                        verbose_name="Choice Value",
                    ),
                ),
                (
                    "product_listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compatibility_values",
                        to="api.productlisting",
                        verbose_name="Product Listing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Compatibility Value",
                "verbose_name_plural": "Product Compatibility Values",
                "unique_together": {("product_listing", "attribute")},
            },
        ),
    ]
