# Generated by Django 5.2 on 2025-08-28 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0068_compatibilitygroup_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productcompatibilityvalue",
            name="choice_value",
        ),
        migrations.AlterUniqueTogether(
            name="productcompatibilityvalue",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="productcompatibilityvalue",
            name="attribute",
        ),
        migrations.RemoveField(
            model_name="productcompatibilityvalue",
            name="product_listing",
        ),
        migrations.AlterField(
            model_name="compatibilityattribute",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributes",
                to="api.compatibilitygroup",
                verbose_name="Compatibility Group",
            ),
        ),
        migrations.CreateModel(
            name="CompatibilityAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=255, verbose_name="Value")),
                (
                    "display_name",
                    models.CharField(max_length=255, verbose_name="Display Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="api.compatibilityattribute",
                        verbose_name="Attribute",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compatibility Attribute Value",
                "verbose_name_plural": "Compatibility Attribute Values",
                "ordering": ["attribute", "display_name"],
                "unique_together": {("attribute", "value")},
            },
        ),
        migrations.AddField(
            model_name="productlisting",
            name="compatibility_attributes",
            field=models.ManyToManyField(
                blank=True,
                help_text="What attributes this product HAS (e.g., this frame IS Carbon, Large)",
                related_name="products_with_attribute",
                to="api.compatibilityattributevalue",
                verbose_name="Product Attributes",
            ),
        ),
        migrations.AddField(
            model_name="productlisting",
            name="compatible_with",
            field=models.ManyToManyField(
                blank=True,
                help_text="What attributes this product is COMPATIBLE with (e.g., this component works with Carbon frames)",
                related_name="compatible_products",
                to="api.compatibilityattributevalue",
                verbose_name="Compatible With",
            ),
        ),
        migrations.DeleteModel(
            name="CompatibilityAttributeChoice",
        ),
        migrations.DeleteModel(
            name="ProductCompatibilityValue",
        ),
    ]
