# Generated by Django 5.2 on 2025-08-29 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0069_remove_productcompatibilityvalue_choice_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="api.productlisting",
                verbose_name="Product Listing",
            ),
        ),
    ]
