# Generated by Django 5.2 on 2025-08-29 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0070_alter_product_product_listing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariantimage",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_images",
                to="api.product",
            ),
        ),
    ]
