# Generated by Django 5.2 on 2025-08-29 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0071_alter_productvariantimage_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariantimage",
            name="listing",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variant_images",
                to="api.productlisting",
            ),
        ),
    ]
