# Generated by Django 5.2 on 2025-08-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0072_productvariantimage_listing"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicequeue",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("completed", "Completed")],
                default="pending",
                max_length=50,
                verbose_name="Queue Status",
            ),
        ),
    ]
