# Generated by Django 5.2 on 2025-10-09 06:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatticket",
            name="assigned_staff",
        ),
        migrations.RemoveField(
            model_name="chatticket",
            name="customer",
        ),
        migrations.DeleteModel(
            name="ChatMessage",
        ),
        migrations.DeleteModel(
            name="ChatTicket",
        ),
    ]
