# Generated by Django 5.2 on 2025-04-19 18:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pos", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product",
        ),
    ]
