"""
Django settings for pedal_point project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import logging
from dotenv import load_dotenv
from google.oauth2 import service_account
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY", "django-insecure-CHANGEME-generate-a-new-secret-key"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True") == "True"

ALLOWED_HOSTS = [
    "pedal-point.onrender.com",
    "pedal-point-yz8e.onrender.com",  # Update with your actual backend URL
    "pdpbackend.share.zrok.io",
    "localhost",
    "127.0.0.1",
    "127.0.0.1",
    "192.168.1.123",
    "192.168.56.1",
    "0.0.0.0",
    # Allow all local network IPs (192.168.x.x, 10.x.x.x, 172.16-31.x.x)  # Allow all hosts for development - remove in production
]


# Application definition

INSTALLED_APPS = [
    "daphne",
    "api.apps.ApiConfig",
    # third party
    "grappelli",
    "nested_admin",
    "livereload",
    "rest_framework",
    "corsheaders",
    "storages",
    "tinymce",
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.facebook",
    "allauth.mfa",
    "allauth.headless",
    "channels",
    # django-otp for 2FA
    "django_otp",
    "django_otp.plugins.otp_totp",
    "django_otp.plugins.otp_static",
    # default
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django_otp.middleware.OTPMiddleware",  # Must be after AuthenticationMiddleware
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "livereload.middleware.LiveReloadScript",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "pedal_point.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "pedal_point.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use PostgreSQL on production (Render), SQLite for local development
DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL:
    # Production: Use PostgreSQL from Render
    DATABASES = {
        "default": dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Development: Use SQLite
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Singapore"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

USE_GCS_STORAGE = os.getenv("USE_GCS_STORAGE", "true").lower() in ["1", "true", "yes"]
GS_BUCKET_NAME = os.getenv("GS_BUCKET_NAME")
GOOGLE_CREDENTIALS_PATH = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")

if (
    USE_GCS_STORAGE
    and GS_BUCKET_NAME
    and GOOGLE_CREDENTIALS_PATH
    and os.path.exists(GOOGLE_CREDENTIALS_PATH)
):
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
            "OPTIONS": {
                "project_id": os.getenv("GS_PROJECT_ID"),
                "credentials": service_account.Credentials.from_service_account_file(
                    GOOGLE_CREDENTIALS_PATH
                ),
                "bucket_name": GS_BUCKET_NAME,
                "location": "media",
                "file_overwrite": False,
            },
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    MEDIA_URL = f"https://storage.googleapis.com/{GS_BUCKET_NAME}/"
else:
    if USE_GCS_STORAGE and not GS_BUCKET_NAME:
        logging.warning(
            "USE_GCS_STORAGE is enabled but GS_BUCKET_NAME is not set. Falling back to local media storage."
        )
    if USE_GCS_STORAGE and GS_BUCKET_NAME and not GOOGLE_CREDENTIALS_PATH:
        logging.warning(
            "USE_GCS_STORAGE is enabled but GOOGLE_APPLICATION_CREDENTIALS is not set. Falling back to local media storage."
        )
    if USE_GCS_STORAGE and GOOGLE_CREDENTIALS_PATH and not os.path.exists(GOOGLE_CREDENTIALS_PATH):
        logging.warning(
            "USE_GCS_STORAGE is enabled but GOOGLE_APPLICATION_CREDENTIALS path is invalid. Falling back to local media storage."
        )

    MEDIA_ROOT = BASE_DIR / "media"
    MEDIA_URL = "/media/"

    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
            "OPTIONS": {
                "location": MEDIA_ROOT,
            },
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    GS_BUCKET_NAME = None

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Sites framework
SITE_ID = 1

# Django-allauth Social Account Settings
# Get backend URL - django-allauth uses this to construct OAuth redirect URIs
BACKEND_URL = os.getenv("BACKEND_URL", "https://pedal-point.onrender.com")

# AI provider configuration (OpenRouter)
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
OPENROUTER_MODEL = os.getenv("OPENROUTER_MODEL", "anthropic/claude-3-haiku")
OPENROUTER_BASE_URL = os.getenv("OPENROUTER_BASE_URL", "https://openrouter.ai/api/v1")

# Social Account Provider Settings
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
        "APP": {
            "client_id": os.getenv("GOOGLE_OAUTH_CLIENT_ID", ""),
            "secret": os.getenv("GOOGLE_OAUTH_CLIENT_SECRET", ""),
            "key": "",
        },
    },
    "facebook": {
        "METHOD": "oauth2",
        "SDK_URL": "//connect.facebook.net/{locale}/sdk.js",
        "SCOPE": ["email", "public_profile"],
        "AUTH_PARAMS": {"auth_type": "reauthenticate"},
        "INIT_PARAMS": {"cookie": True},
        "FIELDS": [
            "id",
            "first_name",
            "last_name",
            "middle_name",
            "name",
            "name_format",
            "picture",
            "short_name",
        ],
        "EXCHANGE_TOKEN": True,
        "LOCALE_FUNC": "path.to.callable",
        "VERIFIED_EMAIL": False,
        "VERSION": "v18.0",
        "APP": {
            "client_id": os.getenv("FACEBOOK_APP_ID", ""),
            "secret": os.getenv("FACEBOOK_APP_SECRET", ""),
            "key": "",
        },
    },
}

# Custom SocialAccountAdapter to handle multiple SocialApp entries
SOCIALACCOUNT_ADAPTER = "pedal_point.socialaccount_adapter.CustomSocialAccountAdapter"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",  # default Django auth
    "allauth.account.auth_backends.AuthenticationBackend",  # Allauth
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.SessionAuthentication",
    ),
}

from corsheaders.defaults import default_headers

CORS_ALLOW_HEADERS = (
    *default_headers,
    "x-session-token",
    "x-email-verification-key",
    "x-password-reset-key",
)

# PayMongo Configuration
PAYMONGO_PUBLIC_KEY = os.getenv("PAYMONGO_PUBLIC", "")
PAYMONGO_SECRET_KEY = os.getenv("PAYMONGO_SECRET", "")
PAYMONGO_BASE_URL = "https://api.paymongo.com/v1"

# Frontend URLs
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:5173")
LOCAL_URL = os.getenv("LOCAL_URL", "http://localhost:5173")


HEADLESS_FRONTEND_URLS = {
    "account_confirm_email": f"{FRONTEND_URL}/verify-email/{{key}}",
    "account_reset_password": f"{FRONTEND_URL}/reset-password",
    "account_reset_password_from_key": f"{FRONTEND_URL}/reset-password/{{key}}",
    "account_signup": f"{FRONTEND_URL}/signup",
    "socialaccount_login_error": f"{FRONTEND_URL}/login?error=social",
    "socialaccount_signup": f"{FRONTEND_URL}/auth/callback",
}

HEADLESS_ONLY = True

# Redirect to frontend login page after email confirmation
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = f"{FRONTEND_URL}/login"
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = f"{FRONTEND_URL}/login"

# Password reset settings
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
PASSWORD_RESET_TIMEOUT = 86400  # 24 hours in seconds


# Add these to your existing settings
# Determine if we're in production (has DATABASE_URL) or local dev
IS_PRODUCTION = os.getenv("IS_PRODUCTION")
print(IS_PRODUCTION)
DOMAIN = os.getenv("DOMAIN")
# print(DOMAIN)

# Proxy/SSL Configuration for Render.com (or other reverse proxies)
# This tells Django to trust the X-Forwarded-Proto header from the proxy
# so it knows when the original request was HTTPS
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# Cookie Settings - Environment Aware
if IS_PRODUCTION:
    # Production (HTTPS) - SameSite=None requires Secure=True
    SESSION_COOKIE_SAMESITE = "None"
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SAMESITE = "None"
    CSRF_COOKIE_SECURE = True
else:
    # Local Development (HTTP) - Can use Lax
    SESSION_COOKIE_SAMESITE = "Lax"
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SECURE = False

# Cookie domain settings - MUST be None for cross-origin to work
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_PATH = "/"
SESSION_COOKIE_DOMAIN = None  # Must be None for cross-origin
SESSION_COOKIE_AGE = 1209600  # 2 weeks

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "https://pedalpoint.share.zrok.io",
    "https://pedalpoint-frontend.onrender.com",
    FRONTEND_URL,
    LOCAL_URL,
]

CSRF_COOKIE_HTTPONLY = False  # Must be False for JavaScript access
CSRF_COOKIE_DOMAIN = None  # Must be None for cross-origin
CSRF_COOKIE_PATH = "/"
CSRF_COOKIE_NAME = "csrftoken"  # Explicitly set the cookie name
CSRF_USE_SESSIONS = False  # Important for API usage
CSRF_HEADER_NAME = "HTTP_X_CSRFTOKEN"  # Header name Django expects
CSRF_COOKIE_AGE = 31449600  # 1 year

ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]


# Prevent automatic login after signup
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = False
# ACCOUNT_EMAIL_VERIFICATION already set above
ACCOUNT_EMAIL_NOTIFICATIONS = True  # General account notifications
ACCOUNT_EMAIL_SUBJECT_PREFIX = ""

# Note: MFA notification emails are handled by custom MFA_ADAPTER (see below)


# Email Configuration - Using console backend for development
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "pedal.point01@gmail.com"
EMAIL_HOST_PASSWORD = "isbp mpuf gzti jtob"
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
# Email recipients for inventory alerts (comma-separated env var or default sender)
INVENTORY_ALERT_RECIPIENTS = [
    email.strip()
    for email in os.getenv(
        "INVENTORY_ALERT_RECIPIENTS",
        DEFAULT_FROM_EMAIL,
    ).split(",")
    if email.strip()
]
# isbp mpuf gzti jtob - new


CORS_ALLOW_ALL_ORIGINS = False  # Use CORS_ALLOWED_ORIGINS instead


CSRF_TRUSTED_ORIGINS = [
    # Local development
    "http://localhost:3000",
    "http://localhost:5173",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:5173",
    "http://192.168.1.123:5173",
    "http://192.168.56.1:5173",
    # Production URLs
    "https://pedalpoint-frontend.onrender.com",
    "https://pedal-point.onrender.com",
    "https://pedalpoint.share.zrok.io",
]

# Add environment-based URLs if they're not already in the list
if FRONTEND_URL and FRONTEND_URL not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append(FRONTEND_URL)
if LOCAL_URL and LOCAL_URL not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append(LOCAL_URL)

# Channels Configuration
ASGI_APPLICATION = "pedal_point.asgi.application"

# Channel Layers Configuration - Using in-memory channel layer (no Redis required)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}

# Redirects
LOGIN_REDIRECT_URL = f"{FRONTEND_URL}/"
ACCOUNT_LOGOUT_REDIRECT_URL = f"{FRONTEND_URL}/login"

# MFA Configuration - Use custom adapter to skip email notifications during dev
MFA_ADAPTER = "pedal_point.mfa_adapter.NoEmailMFAAdapter"
