# Generated by Django 5.2 on 2025-05-20 14:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product",
        ),
    ]
